name: "Release"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generateMatrix:
    runs-on: ubuntu-latest
    outputs:
      featuresJSON: ${{ steps.setMatrix.outputs.featuresJSON }}
    steps:
      - uses: actions/checkout@v4
      - id: setMatrix
        run: |
          featureList=$(ls -d ./features/*/ | xargs -n1 basename | jq -R . | jq -c -s .)
          echo "featuresJSON=${featureList}" >> $GITHUB_OUTPUT
          cd ..

  deletePackages:
    needs: generateMatrix
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        feature: ${{ fromJSON(needs.generateMatrix.outputs.featuresJSON) }}
    steps:
      - name: Delete package for ${{ matrix.feature }}
        run: |
          PACKAGE_NAME="features/${{ matrix.feature }}"
          PACKAGE_TYPE="container"
          GH_TOKEN="${{ secrets.GITHUB_TOKEN }}"

          PACKAGE_ID=$(gh api -H "Accept: application/vnd.github+json" /user/packages/${PACKAGE_TYPE}/${PACKAGE_NAME} --jq '.id' 2>/dev/null || true)
          if [ -n "$PACKAGE_ID" ]; then
            gh api --method DELETE -H "Accept: application/vnd.github+json" /user/packages/${PACKAGE_TYPE}/${PACKAGE_NAME}
            echo "Deleted package $PACKAGE_NAME"
          else
            echo "Package $PACKAGE_NAME not found, skipping."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publishFeatures:
    needs: deletePackages
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features"
          generate-docs: "false"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
