name: "Release"
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generateMatrix:
    runs-on: ubuntu-latest
    outputs:
      featuresJSON: ${{ steps.setMatrix.outputs.featuresJSON }}
    steps:
      - uses: actions/checkout@v4
      - id: setMatrix
        run: |
          featureList=$(ls -d ./features/*/ | xargs -n1 basename | jq -R . | jq -c -s .)
          echo "featuresJSON=${featureList}" >> $GITHUB_OUTPUT
          cd ..

  deletePackages:
    needs: generateMatrix
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        feature: ${{ fromJSON(needs.generateMatrix.outputs.featuresJSON) }}
    steps:
      - name: Delete latest version for ${{ matrix.feature }}
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.feature }}
          package-type: "container"
          min-versions-to-keep: 0

  publishFeatures:
    needs: deletePackages
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: "Publish Features"
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features"
          generate-docs: "false"

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
